name: hallhelp
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_bloc: ^8.1.6
  bloc: ^8.1.4
  cloud_firestore: ^5.4.4
  firebase_auth: ^5.3.1
  firebase_storage: ^12.3.2
  firebase_core: ^3.6.0
  awesome_dialog: ^3.2.1
  http: ^1.2.2
  webview_flutter: ^4.2.1
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.0

flutter_launcher_icons:
  android: true
  image_path: "assets/x.png"

flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
